const element = document.getElementById('selectme')
console.log (element)
const Element = document.getElementsByClassName('heading')
console.log(Element)
const eLement = document.getElementsByTagName('h2')
console.log(eLement)
const elEment = document.querySelector('.heading')
console.log(elEment)